package DataDictionaryNew.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import DataDictionaryNew.behavior.AbstractField__BehaviorDescriptor;

public class Aggregation_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.newLine();
    tgs.append("public class ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    tgs.append(" {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    for (SNode af : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, 0x62cd8899af6e8d72L, "fieldList")))) {
      tgs.indent();
      tgs.append("private ");

      {
        final SNode aField = af;
        if (SNodeOperations.isInstanceOf(aField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af79708bL, "DataDictionaryNew.structure.StructureAsAField"))) {
          tgs.appendNode(aField);
          tgs.append(" ");
        }
      }

      {
        final SNode field = af;
        if (SNodeOperations.isInstanceOf(field, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd98L, "DataDictionaryNew.structure.Field"))) {
          for (SNode fd : ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, 0x62cd8899af6e8d74L, "definitionForFields")), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6e8d6cL, 0x62cd8899af6e8d6dL, "fieldDefinitionList")))) {
            if (SPropertyOperations.getString(SLinkOperations.getTarget(fd, MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd9bL, 0x62cd8899af6e57beL, "field")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) == SPropertyOperations.getString(af, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"))) {
              tgs.appendNode(SLinkOperations.getTarget(fd, MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd9bL, 0x62cd8899af6e57b8L, "domen")));
              tgs.append(" ");
            }
          }
        }
      }

      tgs.append(SPropertyOperations.getString(af, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
      tgs.append(";");
      tgs.newLine();

    }
    tgs.indent();
    tgs.newLine();
    tgs.indent();
    tgs.append("public ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    tgs.append("(); ");
    tgs.newLine();

    for (SNode af : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, 0x62cd8899af6e8d72L, "fieldList")))) {
      tgs.newLine();
      tgs.indent();
      tgs.append("public ");

      {
        final SNode aField = af;
        if (SNodeOperations.isInstanceOf(aField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af79708bL, "DataDictionaryNew.structure.StructureAsAField"))) {
          tgs.appendNode(aField);
          tgs.append(" ");
        }
      }

      {
        final SNode field = af;
        if (SNodeOperations.isInstanceOf(field, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd98L, "DataDictionaryNew.structure.Field"))) {
          for (SNode fd : ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, 0x62cd8899af6e8d74L, "definitionForFields")), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6e8d6cL, 0x62cd8899af6e8d6dL, "fieldDefinitionList")))) {
            if (SPropertyOperations.getString(SLinkOperations.getTarget(fd, MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd9bL, 0x62cd8899af6e57beL, "field")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) == SPropertyOperations.getString(af, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"))) {
              tgs.appendNode(SLinkOperations.getTarget(fd, MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd9bL, 0x62cd8899af6e57b8L, "domen")));
              tgs.append(" ");
            }
          }
        }
      }

      tgs.append(AbstractField__BehaviorDescriptor.getterName_id2w1wJLn_92t.invoke(af));
      tgs.append("()");
      tgs.append("{");
      tgs.newLine();
      tgs.indent();
      tgs.indent();
      tgs.append("return ");
      tgs.append(SPropertyOperations.getString(af, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
      tgs.append(";");
      tgs.newLine();
      tgs.indent();
      tgs.append("}");
      tgs.newLine();

      tgs.newLine();
      tgs.indent();
      tgs.append("piblic ");
      tgs.append(AbstractField__BehaviorDescriptor.setterName_id2w1wJLn_6zc.invoke(af));
      tgs.append("(");

      {
        final SNode aField = af;
        if (SNodeOperations.isInstanceOf(aField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af79708bL, "DataDictionaryNew.structure.StructureAsAField"))) {
          tgs.appendNode(aField);
          tgs.append(" ");
        }
      }

      {
        final SNode field = af;
        if (SNodeOperations.isInstanceOf(field, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd98L, "DataDictionaryNew.structure.Field"))) {
          for (SNode fd : ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, 0x62cd8899af6e8d74L, "definitionForFields")), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6e8d6cL, 0x62cd8899af6e8d6dL, "fieldDefinitionList")))) {
            if (SPropertyOperations.getString(SLinkOperations.getTarget(fd, MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd9bL, 0x62cd8899af6e57beL, "field")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) == SPropertyOperations.getString(af, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"))) {
              tgs.appendNode(SLinkOperations.getTarget(fd, MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd9bL, 0x62cd8899af6e57b8L, "domen")));
              tgs.append(" ");
            }
          }
        }
      }
      tgs.append("val) {");
      tgs.newLine();

      tgs.indent();
      tgs.indent();
      tgs.append("this.");
      tgs.append(SPropertyOperations.getString(af, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
      tgs.append(" = ");
      tgs.append("val");
      tgs.append(";");
      tgs.newLine();
      tgs.indent();
      tgs.append("}");
      tgs.newLine();
    }

    ctx.getBuffer().area().decreaseIndent();

    tgs.append(" }");
    tgs.newLine();
  }
}
