package DataDictionaryNew.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class AbstractField_Behavior {
  public static String call_setterName_2882729256806541516(SNode __thisNode__) {
    return AbstractField__BehaviorDescriptor.setterName_id2w1wJLn_6zc(__thisNode__);
  }
  public static String call_getterName_2882729256806551709(SNode __thisNode__) {
    return AbstractField__BehaviorDescriptor.getterName_id2w1wJLn_92t(__thisNode__);
  }
}
